In [1]:
import numpy as np

In [9]:
a = np.array([3,7,5,4,10])

In [10]:
print(a)

[ 3  7  5  4 10]


In [11]:
# chi binh phuong cac so chan
index = np.where(a % 2 ==0)

In [12]:
print(index)

(array([3, 4], dtype=int64),)


In [13]:
b = np.array([a[i]**2 for i in index])

In [14]:
print(b)

[[ 16 100]]


In [15]:
a[tuple(index)] = b

In [16]:
print(a)

[  3   7   5  16 100]


In [17]:
a = np.array([3,7,5,4,10])

In [20]:
print(a.sum())

131


In [21]:
print(a.min())

3


In [22]:
print(a.max())

100


In [34]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [36]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [37]:
print(a.shape)

(2, 5)


In [38]:
print(a.size)

10


In [39]:
# tao mang 2 chieu gom 2 dong 5 cot
# dong 0 gom cac cot la so chan va dong 1 gom cac cot la so le
a = np.array([np.arange(0,10,2),np.arange(1,10,2)])

In [40]:
print(a)

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [41]:
a = np.arange(24)

In [42]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [43]:
b = a.reshape(4,6)

In [44]:
print(b)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [45]:
c = a.reshape(3,2,4)

In [46]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [48]:
# Lay ra dong thu 0 cua ma tran vi tri 2
print(c[2,0])

[16 17 18 19]


In [49]:
# Lay ra cot thu 0 cua ma tran vi tri 1
print(c[1,...,0])

[ 8 12]


In [50]:
print(c[1][1])

[12 13 14 15]
